# Practical example 2: Testing code in our module (cont.)

There is one very important reason for demonstrating that a test will fail
before you write the code that makes it pass: Showing a failing test is how we
test the tests.

If we accidentally wrote a test that never fails, but we wrote it after
implementing the functionality in our module, how would we tell the difference
between a broken test and well-functioning module code?

```python using_pytest/__init__.py
def add(x, y):
    return x + y

def multiply(x, y):
    return x * y
```
